; Add this context to your extensions.conf
; and include german-training in your outbound context:
;   [call-out]
;   include => german-training
;
; Requires macro-monitor to be defined (records calls to WAV via MixMonitor).
; Example macro-monitor definition:
;
; [macro-monitor]
; exten => s,1,Set(Filename=${STRFTIME(${EPOCH},,%Y.%m.%d_%H-%M)}_From.${CALLERID(number)}_To.${Exten})
;  same => n,Set(Now=${EPOCH})
;  same => n,Set(Day=${STRFTIME(${Now},,%d)})
;  same => n,Set(Month=${STRFTIME(${Now},,%m)})
;  same => n,Set(Year=${STRFTIME(${Now},,%Y)})
;  same => n,Set(Dir=/usr/local/var/www/asterisk-records)
;  same => n,Set(Recdir=${Dir}/${Year}/${Month}/${Day})
;  same => n,MixMonitor(${Recdir}/${Filename}.wav,b)
;  same => n,Set(CDR(recordingpath)=${Recdir}/${Filename}.wav)

[german-training]
exten => 555,1,Answer()
 same => n,Macro(monitor)
 same => n,AGI(german_trainer_wrapper)
 same => n,Hangup()
